[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
description = "An edit of the mod Lethal Interns with the intent of making the Interns more like player bots"
websiteUrl = "https://github.com/T-Rizzle12/Lethal-Bots"
containsNsfwContent = false
[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"
Evaisa-LethalLib = "0.16.1"
Sigurd-CSync = "5.0.1"
Rune580-LethalCompany_InputUtils = "0.7.4"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./Packages"

[[build.copy]]
source = "../bin/Release/netstandard2.1/LethalBots.dll"
target = "plugins/TRizzle-LethalBot/"

[[build.copy]]
source = "../UnityProject/AssetBundles/StandaloneWindows/lethalbotnpcmodassets"
target = "plugins/TRizzle-LethalBot/"

[[build.copy]]
source = "./CHANGELOG.md"
target = "/"

[publish]
communities = [ "lethal-company", ]
[publish.categories]
# Get the list of categories from https://thunderstore.io/api/experimental/community/lethal-company/category/
lethal-company = [ "bepinex", "clientside", "serverside", "tweaks-and-quality-of-life", "equipment", "mods", ]